export const colors = {
    primary_Blue: '#004A7F',
    primary_Red: '#AE282E',
    Black: '#000000',
    secondary_Black: '#000000',
    secondary_Grey: '#979797',
    secondary_Red: '#FF0000',
    secondary_Pink: '#FFF1F0',
    secondary_Light_Red: '#FF3A29',
    secondary_Green: '#27AE60',
    secondary_light_Green: '#EFFBF0',
    secondary_Medium_Green: '#34B53A',
    secondary_Dark_Blue: '#2672AB',
    secondary_Sky_Blue: '#02A0FC',
    secondary_Light_Blue: '#EAF6FF',
    secondary_Dark_Grey: '#E0E5EC',
    secondary_Orange: '#FF8B2D',
    secondary_Light_Orange: '#FFE5D3',
    secondary_Medium_Orange: '#FFB200',
    Pure_White: '#FFF',
  }