
export default {
  // AUTH SCREEN
  LOADING_SCREEN: "LOADING_SCREEN",
  LOGIN_SCREEN: "LOGIN_SCREEN",
  SIGNUP_SCREEN: "SIGNUP_SCREEN",
  LOGOUT_SCREEN: "LOGOUT_SCREEN",
  ADD_BIKE: "ADD_BIKE",

  // BOTTOM SCREEN  

  TABS: "TABS",
  HOME_SCREEN: "HOME_SCREEN",
  LOAN_SCREEN: "LOAN_SCREEN",
  BOOKING_SCREEN: "BOOKINF_SCREEN",
  PROFILE_SCREEN: "PROFILE_SCREEN",

  // MAIN SCREEN 
  SEARCH_SCREEN: "SEARCH_SCREEN",
  LISTING_SCREEN: "LISTING_SCREEN",
  SERVICE_CART: "SERCICE_CART",
  RENTAL_VEHICLE: "RENTAL_VEHICLE",
  SERVICE_DETAIL: "SERVICE_DETAIL",
  APPOINTMENT_DETAIL: "APPOINTMENT_DETAIL",
  APPOINTMENT_SCREEN: "APPOINTMENT_SCREEN",
  CONFIRM_BOOKING_SCREEN: "CONFIRM_BOOKING_SCREEN",
  BOOKING_BLANK_SCREEN: "BOOKING_BLANK_SCREEN",

  //MANAGE BOOKINGS SCREENS
  BOOKINGS_SCREEN: "BOOKINGS_SCREEN",
  FEEDBACK_SCREEN: "FEEDBACK_SCREEN",
  ACCEPTED_SCREEN: "ACCEPTED_SCREEN",
  COMPLETED_SCREEN: "COMPLETED_SCREEN",

  //USER PROFILE  SCEREENS 
  PROFILE_SCREEN: "PROFILE_SCREEN",
  EDIT_PROFILE_SCREEN: "EDIT_PROFILE_SCREEN",
  SHARE_SCREEN: "SHARE_SCREEN",
  FAQ_SCREEN: "FAQ_SCREEN",
  PRIVACY_POLICY_SCREEN: "PRIVACY_POLICY_SCREEN",
  
  //LOAN MODULE SCEREENS 
  LOAN_SCREEN: "LOAN_SCREEN",
  LOAN_DETAIL_SCREEN: "LOAN_DETAIL_SCREEN",
  LOAN_LIST_SCREEN: "LOAN_LIST_SCREEN",
}
